### DISCUSSION TITLE
I would need a way to include / exclude contents

### DISCUSSION THREAD

**Discussion by parmentelat** [jupyter-book/mystmd#1236] [Q&A]
unless I missed it, there seems to be a way to exclude stuff, but no way to include stuff
I mean, these pages
https://jupyterbook.org/en/stable/content/execute.html#exclude-files-from-execution
https://jupyterbook.org/en/stable/structure/configure.html#exclude-pages-from-your-build
mention an `exclude_patterns` setting, but nothing about including

### my use case

I typically have a collection of notebooks, each with any number of artefacts (python modules, accessory markdown files, etc..)
also the notebooks are all jupytext-encoded as `.py` or `.md` files
for that reason I have adopted a naming convention, so that notebooks stick out as `*-nb.py` or `*-nb.md`
having the ability to use this as the basis for selecting material would be so much more convenient than having to exclude the artefacts, that do not follow any particular scheme !

### a possible inspiration

of course there is a need to specify how inclusion and exclusion could coexist
in this respect we have the example of `rsync` that allows for such a mechanism
see e.g. https://shallowsky.com/blog/linux/cmdline/rsync-include-exclude.html
a possible data model for this configuration could then become
```yaml
patterns:
  - type: include
    pattern: **/*-nb.py
  - type: include
    pattern: **/*-nb.md
  - type: exclude
    pattern: **/*
```

### compatibility

and for compatibility of course `exclude_patterns` could be still supported and compiled into 
```yaml
patterns:
  - type: exclude
    pattern: pattern1
  - type: exclude
    pattern: pattern2
  - ...
  - type: include
    pattern: **/*
```

just a thought....
