### DISCUSSION TITLE
How to use sections in a myst article site?

### DISCUSSION THREAD

**Discussion by matthewfeickert** [jupyter-book/mystmd#1237] [Q&A] [answered]
When writing a paper, like the [SciPy 2024 proceedings](https://github.com/scipy-conference/scipy_proceedings/tree/2024), if you are working with collaborators it is often highly desirable/necessary to split the paper text out into multiple files so that you do not continually encountere merge conflicts when writing asynchronously in a PR-based workflow. In LaTeX you would normally do this by using `\include` or `\input` directives like

```latex
...
\abstract{%
 \input{src/abstract}
}
%
\maketitle
%

\input{src/introduction.tex}

...

\input{src/conclusions.tex}
...
```

In the Jupyter Book [Structure the Table of Contents](https://jupyterbook.org/en/stable/structure/toc.html) docs it shows that you can [structure a single page article from multiple input files](https://jupyterbook.org/en/stable/structure/toc.html#build-an-article-from-multiple-files) using a `_toc.yml` file structure like

```yaml
format: jb-article
root: index
sections:
- file: path/to/chapter1
- file: path/to/chapter2
```

and the `--builder singlehtml` option to `jupyter-book build`.

However, when trying to do this with `mystmd` `v1.2.4` there doesn't seem to be this option for `myst start` or `myst build`. If in `myst.yml` a user is using 

```yaml
...
site:
  template: article-theme
```

is it possible to create a multiple input file paper? So something akin to changing

```latex

\input{src/introduction.tex}

...

\input{src/conclusions.tex}
```

for

```yaml
...
sections:
- file: introduction.md
...
- file: conclusions.md
```
?

## Relevant GitHub Issues and PRs

* https://github.com/matthewfeickert/draft-scipy-2024-proceedings-submission/pull/13
