### DISCUSSION TITLE
Link notebooks for figures but not add to TOC?

### DISCUSSION THREAD

**Discussion by brookisme** [jupyter-book/mystmd#1700] [Q&A]
Hi Everyone - I'm wanting to include figures from python-notebooks.  Similar to this https://mystmd.org/guide/reuse-jupyter-outputs#outputs-as-figures.

To get it to work I need to include the notebook in my TOC, as in the last page listed here:

```yaml
toc:
    - file: myst/main.md
    - file: myst/sections/intro.md
    - file: myst/sections/data.md
    - file: myst/sections/scripts.md
    - file: myst/nb/spectral_trends.ipynb
 ```
 
 Which leads to a link on (what should be) the last page
 
<img width="605" alt="Screenshot 2024-12-15 at 12 13 30 PM" src="https://github.com/user-attachments/assets/7943558a-c8d8-4b16-8af0-309fdc15f101" />

Is there anyway to link the notebook for figure inclusion without adding it as a page?   Note I'm fine if the notebook has a public-url, I just don't want there to be links to it
 
Thanks!
