### DISCUSSION TITLE
How to reference an entire markdown cell or collection of content instead of just the first paragraph

### DISCUSSION THREAD

**Discussion by atharvaaalok** [jupyter-book/mystmd#1821] [Q&A] [answered]
I have the following markdown cell:
```
We see an exciting improvement! Injective Networks with `PReLU` do much better. This gives us the
following insight:
:::{card}
Injective Networks are **parameter deficient**.

Adding parameters gives them much more representation power.
:::
```

I wish to reference this in some other part of my code so I add the following label:
```
(parameter_insight)=
We see an exciting improvement! Injective Networks with `PReLU` do much better. This gives us the
following insight:
:::{card}
Injective Networks are **parameter deficient**.

Adding parameters gives them much more representation power.
:::
```

But when I reference it somewhere else as follows:
```
We discussed [earlier](#parameter_insight)
```
Only the following shows up when I hover over the reference link:
"We see an exciting improvement! Injective Networks with `PReLU` do much better. This gives us the
following insight:"
The card doesn't show up.

How can I solve this issue?

**Comment by agoose77** [comment, marked as answer]
When you write something like
````markdown
We see an exciting improvement! Injective Networks with `PReLU` do much better. This gives us the
following insight:
:::{card}
Injective Networks are **parameter deficient**.

Adding parameters gives them much more representation power.
:::
````

what MyST sees is the following syntax tree:
````yaml
type: root
children:
  - type: block
    children:
      - type: paragraph
        children:
          - type: text
            value: 'We see an exciting improvement! Injective Networks with '
          - type: inlineCode
            value: PReLU
          - type: text
            value: |2-
               do much better. This gives us the
              following insight:
      - type: card
        children:
          - type: paragraph
            children:
              - type: text
                value: 'Injective Networks are '
              - type: strong
                children:
                  - type: text
                    value: parameter deficient
              - type: text
                value: .
          - type: paragraph
            children:
              - type: text
                value: Adding parameters gives them much more representation power.

````

When you then add an anchor, it binds to the adjacent block element:
````markdown
(see-this-anchor)=
We see an exciting improvement! Injective Networks with `PReLU` do much better. This gives us the
following insight:
:::{card}
Injective Networks are **parameter deficient**.

Adding parameters gives them much more representation power.
:::
````

````yaml
type: root
children:
  - type: block
    children:
      - type: paragraph
        children:
          - type: text
            value: 'We see an exciting improvement! Injective Networks with '
          - type: inlineCode
            value: PReLU
          - type: text
            value: |2-
               do much better. This gives us the
              following insight:
        label: see-this-anchor
        identifier: see-this-anchor
        html_id: see-this-anchor
      - type: card
        children:
          - type: paragraph
            children:
              - type: text
                value: 'Injective Networks are '
              - type: strong
                children:
                  - type: text
                    value: parameter deficient
              - type: text
                value: .
          - type: paragraph
            children:
              - type: text
                value: Adding parameters gives them much more representation power.

````

This means that when you subsequently reference e.g. `see-this-anchor`, it previews only the paragraph, _not_ the card.

You can solve this by labelling a _parent_ element that contains your Markdown. One useful construct is the `div` directive:

`````markdown
(see-this-anchor)=
::::{div}
We see an exciting improvement! Injective Networks with `PReLU` do much better. This gives us the
following insight:
:::{card}
Injective Networks are **parameter deficient**.

Adding parameters gives them much more representation power.
:::
::::
`````
You'll see that the hover preview for `[](#see-this-anchor)` shows both the card and paragraph. But, the generated text for the link isn't very helpful; you'll need to craft that by hand, e.g. `[see this example again](#see-this-anchor)`

**Comment by choldgraf** [comment]
In addition to @agoose77's answer, I think another option would be to [use markdown blocks syntax and attach metadata to them](https://mystmd.org/guide/blocks#blocks). For example, this syntax:

```
+++ {"label": "hi"}
Hi there.

Everybody.
+++

Some other content
```

Gets parsed to:

```yaml
type: root
children:
  - type: block
    children:
      - type: paragraph
        children:
          - type: text
            value: Hi there.
      - type: paragraph
        children:
          - type: text
            value: Everybody.
    data: {}
    identifier: hi
    label: hi
    html_id: hi
  - type: block
    children:
      - type: paragraph
        children:
          - type: text
            value: Some other content.
```

_note: I've migrated this to the Discussions Forum because it's a helpful question and answer, and doesn't relate to new features etc_
