### DISCUSSION TITLE
Trying to create website through Gitlab CI

### DISCUSSION THREAD

**Discussion by ManuelAndia** [jupyter-book/mystmd#1830] [Q&A]
Hi all, I'm pretty new to MyST and continuous integration so I apologise in advance if my wording is a bit imprecise 😊

I tried looking for similar discussions but struggled to find anything related to my issue, hence this post.

I'm trying to deploy a physics course as a Gitlab "pages" website. I already have a few pages which work great locally with MyST (when I run `myst build --html --all` for instance), including the different `export` formats (PDF, docx etc.).

On the main md page, I have the following lines in the frontmatter:
```
exports:
    - format: docx
      output: ./_build/exports/Index.doc
      id: word-docx
    - format: pdf
      output: ./_build/exports/Index.pdf
      id: pdf-doc
    - format: tex
      output: ./_build/exports/Index.zip
      id: tex-zip
downloads:
  - file: Index.md
    title: This page (source)
  - id: word-docx
    title: This page (Word)
  - id: pdf-doc
    title: This page (PDF)
  - id: tex-zip
    title: This page (LaTeX)
  - file: ./Documents/Example_PDF.pdf
    title: Full course in PDF
```

As I said, locally this does generate the files I require in the `_build/exports` folder.

I then try to push all of this to my Gitlab repo, and I have a `.gitlab-ci.yml` file with the following lines:

```
- myst build --html --all # build HTML and all other exports (PDF, Word etc.)
- mv _build/html/ public/
```

I end up getting an error that I don't get when I use MyST offline (I'm only pasting the first 2 lines because the rest is a lot of the same):

```
💾 Saved template to path _build/templates/tex/myst/curvenote
⛔️ Pages/Index.md 'files.0' file does not exist: _build/templates/tex/myst/curvenote/template.tex (at _build/templates/tex/myst/curvenote/template.yml#template)
```

This results in the PDF and docx documents not being available for download in the page's download options (but for some reason the tex archive is available for download on _some_ pages, not all).

Does anyone have a clue of what could be happening?

Thanks in advance for your help 🙏
Cheers
Manuel
