### DISCUSSION TITLE
Chapter numbering in website template

### DISCUSSION THREAD

**Discussion by cpraveen** [jupyter-book/mystmd#1863] [Q&A]
I have enabled chapter numbering in my website, but I find the numbering bit wrong. See here

https://cpraveen.github.io/numa/approx

Numbering is starting from 7.4 instead of 7.1

<img width="261" alt="Screenshot 2025-02-16 at 5 29 55 PM" src="https://github.com/user-attachments/assets/dd43e4ae-96ae-409b-be98-e305a9687c00" />

The frontmatter in each page looks like this

```
---
exports:
  - format: pdf
kernelspec:
  display_name: Python 3 (ipykernel)
  language: python
  name: python3
numbering:
  code: false
  equation: true
  title: true
  headings: true
---
```

Obviously I am doing something wrong, but could not find the problem.

**Comment by agoose77** [comment]
What is happening here is that the numbering is acting on headings. For some of your sections with children, you have multiple headings on the index page e.g. https://cpraveen.github.io/numa/roots#bracketing-the-root-in-1-d. This means that the numbering for subsequent pages is offset.

@fwkoch this seems intentional, but did we consider other approaches here?

**Comment by cpraveen** [comment]
In the children pages I have tried adding

```
---
numbering:
  code: false
  equation: true
  title: true
  headings:
    enabled: true
    continue: false
---
```

but this does not work.
