### DISCUSSION TITLE
Image on SideBar

### DISCUSSION THREAD

**Discussion by Proteusiq** [jupyter-book/mystmd#1962] [Q&A]
![CleanShot 2025-04-11 at 11 11 49](https://github.com/user-attachments/assets/a547aa44-73a8-46ad-befd-8d9d985f4332)

How do I add png image on top of my title

Jupyter book 2:

```yaml
version: 1
project:
  title: Pragmatic Python
  description: Friends Don’t Let Friends Write Mediocre Code
  keywords:
    - python
    - design pattern
  authors:
    - name: Prayson Wilfred Daniel
  copyright: '2025'
  github: proteusiq/Pragmatic-Python
  bibliography:
    - references.bib
  exports:
    - format: pdf
      template: plain_latex_book
      output: exports/book.pdf
  toc:
    - file: chapters/title.md
      title: Introduction
    - file: chapters/roadmap.md
    - file: chapters/01_beginning.md
site:
  options:
    favicon: favicon.ico
    logo: assets/logo.png
    folders: true
  template: book-theme
```
