### DISCUSSION TITLE
Functions to build ToCs

### DISCUSSION THREAD

**Discussion by JimMadge** [jupyter-book/mystmd#1977] [Q&A]
I'm trying to build a MyST plugin which allows you to curate pages/sections of a book into new ToCs, which could be used as syllabi, or sub-books.
This is different from collecting pages with the same tag, as you have the order and nesting of a ToC.

My current idea is to have a directive, where the body uses the same format at the ToC defined in `myst.yml`, like,

```
:::{curation} my favourites
- file: animals/cats.md
- file: cinemas/prince_charles.md
- file: places/lundy.md
:::
```

which will end up in AST something like,

```yaml
- type: block
  children:
    - type: toc
      children:
        - type: heading
          level: 2
          value: My Favourites
        - type: list
          children:
            - type: ListItem
              children:
                - type: link
                  url: /animals/cats
                  children:
                    - type: text
                      value: Cats
...
```

as when you use the `{toc}` directive.
To make this consistent with other ToCs and avoid duplication, it would be great to use functions/transformations in the MyST packages which do this.

I haven't found quite what I'm looking for.

The `{toc}` [directive](https://github.com/jupyter-book/mystmd/blob/5a12e4b44c41a801ebe4d6b28336bb6c1121e146/packages/myst-directives/src/toc.ts) and [transformation](https://github.com/jupyter-book/mystmd/blob/5a12e4b44c41a801ebe4d6b28336bb6c1121e146/packages/myst-transforms/src/toc.ts) don't let you write a ToC explicitly.
I found a [ToC validations function](https://github.com/jupyter-book/mystmd/blob/5a12e4b44c41a801ebe4d6b28336bb6c1121e146/packages/myst-toc/src/toc.ts#L209) which is helpful.
However, what _I think_ is the [function to process the `toc` item in `myst.yml`](https://github.com/jupyter-book/mystmd/blob/5a12e4b44c41a801ebe4d6b28336bb6c1121e146/packages/myst-cli/src/build/utils/collectExportOptions.ts#L68) looks like it takes arguments about the project.

Is there a function like `structured_data -> ToC_AST` in MyST?
Maybe there is a better way to go about this?
