### ISSUE TITLE
URL entries in Table of Contents

### ISSUE THREAD

**Issue by choldgraf** [jupyter-book/mystmd#1445]
It is helpful to support URL entries in the Table of Contents in case users want to directly point to an internal or external site from the TOC. This is usually most helpful with web exports, but may also be useful for PDF exports as well.

Our documentation already notes this feature, but says they are ignored:

![CleanShot 2024-08-10 at 13 04 58](https://github.com/user-attachments/assets/2caa9e29-2120-404c-863e-4f8e96f4e4cc)

**Comment by brookisme** [comment]
Note the documentation shows:

```yaml
  toc:
    - file: root.md
    - url: 'https://google.com'
```

It would be nice to be able to define the text that is shown.  Maybe:


```yaml
  toc:
    - file: root.md
    - url: [Google]( 'https://google.com')
```

**Comment by parmentelat** [comment]
imho this feature would be very nice to have as it allows to drastically extend the capabilities of myst :)

**Comment by parmentelat** [comment]
@brookisme

as far as text is concerned, I note that in jupyter book the syntax for that is

```yaml
chapters:
  - file: some-file.md
  - file: another-file.md
    title: something to override the first h1 heading
  - url: https://google.com
    title: the google search page
```

I suggest we keep something along those lines if/when url are supported

**Comment by mfisher87** [comment]
This looks naively like a "good first issue". What do you all think?

**Comment by choldgraf** [comment]
I'm not sure - it'll depend on how complex the logic is to parse the toc and decide what to do with the contents. I added a little "implementation" section in the issue body to give some breadcrumbs for where you might go looking to try and implement this.

**Comment by mfisher87** [comment]
Thanks, Chris!!

**Comment by parmentelat** [comment]
in relation to #2098,  we could envision something like 

```yaml
chapters:
  - file: some-file.md
  - file: another-file.md
    title: something to override the first h1 heading
  - url: https://google.com
    title: the google search page
    open_in_new_tab: true       
```

and then the default for that new field could be 
- either `false` if we're lazy
- or it could be set at the config level with something like
  ```yaml
  site.options.open_in_new_tab: true
  ```

if that proposal makes sense to everybody then we could even close #2098
or move this comment to #2098 if that's too far-fetched, let me know
