### ISSUE TITLE
Make the top bar navigation links correctly use BASE_URL whether being run locally or online

### ISSUE THREAD

**Issue by lwasser** [jupyter-book/mystmd#1531]
pyOpenSci is using [mystmd for our metrics dashboard](https://www.pyopensci.org/peer-review-metrics/) - It's been great so far but i'm running into challenges because the top bar navigation doesn't seem to be aware of the base_url when we build hte site in CI. because of this - you can see that our navigation doesn't work - rather it tries to link each page to our core website. 

The current config file looks like this:
```
site:
  nav:
    # top-level nav - these links don't work if you use the path to the file.
    - title: Peer review data
      children:
        - title: Historical data
          url: /historical-peer-review-stats
        - title: Peer review data
          url: /current-reviews-data
    - title: Contributor data
      url: /contributor-pr-issues
    - title: Contributing
      url: /README
```
I was told that the config file could work online IF we modified it to represent our github repo name:

```
site:
  nav:
    # top-level nav - these links don't work if you use the path to the file.
    - title: Peer review data
      children:
        - title: Historical data
          url: /peer-review-metrics/historical-peer-review-stats
        - title: Peer review data
          url: /peer-review-metrics/current-reviews-data
    - title: Contributor data
      url: /peer-review-metrics/contributor-pr-issues
    - title: Contributing
      url: /peer-review-metrics/README
```

This is great and i'll likely make the change so the build works. However, this approach will mean that locally, i won't be able to test links. 

## Proposal

I propose that there is some way to specify the basurl in the config so myst knows to add it when the site is being built in CI. This could even be a config option in the yml file (i think jekyll supports  this?) that will only be used when the site is built in CI.

it's interesting to me that the left hand navigation works well but the top bar doesn't. I would expect them to work the same.  

## Additional notes

Thank you for considering this enhancement!  ✨  and for all of your work on myst!
