### ISSUE TITLE
Document executable markdown files

### ISSUE THREAD

**Issue by rowanc1** [jupyter-book/mystmd#1569]
We likely need something like this in the frontmatter.

```
---
jupytext:
  formats: md:myst
  text_representation:
    extension: .md
    format_name: myst
kernelspec:
  display_name: Python 3
  language: python
  name: python3
---
```

Previous docs page is here:
https://jupyterbook.org/en/stable/file-types/myst-notebooks.html
