### ISSUE TITLE
`toc` entries are rendered in reverse, or alphabetically, sometimes. :(

### ISSUE THREAD

**Issue by sneakers-the-rat** [jupyter-book/mystmd#1641]
## Description

When I do this:

`myst.yml`
```yaml
version: 1
project:
  id: 3447377e-b204-4078-8398-fcc69565b0bf
  toc:
    - file: section_one.md
    - file: section_two.md
    - file: section_three.md
site:
  template: book-theme
```

I get this:

![Image](https://github.com/user-attachments/assets/da5ab014-39a1-40ca-8b4a-e8aeec520a08)

but also when I do this

```yaml
version: 1
project:
  id: 3447377e-b204-4078-8398-fcc69565b0bf
  toc:
    - file: a.md
    - file: b.md
    - file: c.md
    - file: z.md
    - file: f.md
site:
  template: book-theme
```

i get this

![Image](https://github.com/user-attachments/assets/9379399d-f79c-44b1-ad66-9948f9775a5a)

which is correct.

and in my real document which is like this

```yaml
  toc:
    - file: src/index.md
    - file: src/intro/intro.md
      children:
      - file: src/intro/prior_art.md
    - file: src/implementation/implementation.md
      children:
      - file: src/implementation/spec.md
      - file: src/implementation/generators.md
      - file: src/implementation/nwb.md
    - file: src/examples/examples.md
      children:
      - file: src/examples/nwb_linkml.md
    - file: src/discussion/discussion.md
```

i get this

![Image](https://github.com/user-attachments/assets/2dbde613-cd28-47c3-9ca4-ab05ba72dfaf)

which has the first entry in place but the rest reversed for each group.

but if i use a jupyter book ToC the ordering is correct

`src/_toc.yml`
```yaml
format: jb-book
root: index
chapters:
- file: intro/intro
  sections:
  - file: intro/prior_art
- file: implementation/implementation
  sections:
  - file: implementation/spec
  - file: implementation/generators
  - file: implementation/nwb
- file: examples/examples
  sections:
  - file: examples/nwb_linkml
- file: discussion/discussion
```

![Image](https://github.com/user-attachments/assets/1ca83bf9-ba98-4b89-b7e2-5ac30c0e4539)

if i add logger commands at the start and end of this function for `entries` and `pages` they are both in the correct order when loaded here: https://github.com/jupyter-book/mystmd/blob/16a5e5869e10faf069f1fe2b288ffdea858d4345/packages/myst-cli/src/project/fromTOC.ts#L240

and i don't know the best way to trace through to see when it gets reversed, and i'm not sure why the alphabetical example is in the correct order but the `section_one`, etc. example isnt?

## Proposed solution

ideally it would be in the order it's specified in!

## Additional notes

- myst version: `v1.3.18` for all
