### ISSUE TITLE
Executing notebooks in specific order

### ISSUE THREAD

**Issue by agahkarakuzu** [jupyter-book/mystmd#1794]
## Proposal

Currently `myst build --execute` runs executable content asynchronously. However, when notebooks depend on one another, achieving synchronous execution requires hacky solutions, such as making one notebook wait for a specific file created by another.

Also, simultaneous execution can cause issues when multiple resource-intensive notebooks are included, mostly performance bottlenecks.

Would it be possible to introduce a feature in `myst.yml` to specify the execution order of notebooks? Incorporating memory flushing between notebook executions could greatly enhance efficiency and resource management.

Thank you!

**Comment by rowanc1** [comment]
I would be curious if you have a sketch at what some configuration might look like to achieve this?

**Comment by mmmarinho** [comment]
Just giving a heartfelt thumbs up to the first approach, quoted below, although there is a clear use for both proposals. 

> It could be a part of the TOC such as:

```yaml
 toc:
    - file: index.md
    - title: Example chapter
      children:
        - file: intro.md
        - file: notebook1.ipynb
          execution_order: 0
        - file: notebook2.ipynb
          execution_order: 1
        - file: notebook3.ipynb
          execution_order: 0
         
```

To give a concrete example supporting the first case, sometimes users (e.g. me right now) might need different "execution groups", in a scenario without any sort of dependency among notebooks. For instance, when notebooks use different and possibly incompatible packages in which an asynchronous execution would cause nondeterministic failures in execution (#2055).
