### ISSUE TITLE
Improve error message for missing plugin `.mjs` file

### ISSUE THREAD

**Issue by agoose77** [jupyter-book/mystmd#1813]
When running through including a new transform to `mystmd` with @JimMadge, we observed that the error message for a non-existent plugin file isn't clearly referring to a plugin!

**Comment by JimMadge** [comment]
Example output,

```console
❯ npx myst
...
ENOENT: no such file or directory, stat './no-alt-text.mjs'
```

with a configuration like,

```yaml
version: 1
project:
  id: ...
  github: https://github.com/...
  plugins:
    - ./no-alt-text.mjs
site:
  template: book-theme
```
