### ISSUE TITLE
Github Pages - deploying a subfolder, e.g. in `/docs/`

### ISSUE THREAD

**Issue by atharvaaalok** [jupyter-book/mystmd#1849]
I am working on a repository for creating differentiable loss functions:
https://github.com/atharvaaalok/geosimilarity

I have a `docs` folder in which I have MyST markdown code for documentation.
How do I launch a webpage using github pages?

The documentation [here](https://mystmd.org/guide/deployment-github-pages) says to run the following command in the root:
`myst init --gh-pages`

But when I run the `myst` command in my root it uses the `README.md` instead of the markdown files in the `docs/` folder.
What are the exact steps that I have to take to launch github pages?

I first run `myst`command in the `docs/` folder which creates a `_build` folder inside `docs/`. But it also autogenerates a `.gitignore` that ignores the _build folder.
I then run the command `myst init --gh-pages` from the root of the git repository but github pages failed to deploy.
I tried this test on a copy of my repository (so as to keep everything in the main repo organized).

Would also like to automatically generate documentation for the functions and classes defined in `geosimilarity/` using their docstrings.

**Comment by rowanc1** [comment]
You can add a `working-directory: docs` to each `step` in the `deploy` action as well as ensuring that the `./docs/_build/html` is what is uploaded. Something like (untested, let us know what works here please!):

```yaml
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install MyST Markdown
        run: npm install -g mystmd
      - name: Build HTML Assets
        run: myst build --html
        working-directory: docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
