### ISSUE TITLE
sitemap.xml not created automatically

### ISSUE THREAD

**Issue by giswqs** [jupyter-book/mystmd#1976]
The MyST [User Guide](https://mystmd.org/guide/seo-and-social#sitemap-xml) says that `The sitemap.xml is always created and is accessible through [sitemap.xml](https://mystmd.org/sitemap.xml)`. 

However, I could not find the `sitemap.xml` for my site. 

- Repo: https://github.com/giswqs/myst-demo
- GitHub Pages: https://giswqs.github.io/myst-demo

Sitemap link (not working)
https://giswqs.github.io/myst-demo/sitemap.xml

Artifact from GitHub Pages
![Image](https://github.com/user-attachments/assets/6884d54a-1716-4664-9ac5-4f6f54858a11)

**Comment by vangeest** [comment]
I experience the same problem, it seems to be bound to static-hosted sites.

**Comment by ayghri** [comment]
The issue comes from `packages/myst-cli/src/build/html/index.ts ` line 58:

```js
        ...['robots.txt', 'myst-theme.css'].map((asset) => ({
```
I think it should be:
```js
        ...['robots.txt', 'myst-theme.css', 'sitemap.xml', 'sitemap_style.xsl'].map((asset) => ({
```

but that does not solve the entire problem, as `sitemap.xml` and other files such as `robot.txt` will still use `localhost:3000`...

I have created a fork that changes index.ts, and my github workflow now uses it.

Here's my current workflow that solves this, replace with your own domain:


```yaml
name: MyST GitHub Pages Deploy
on:
  push:
    branches: [main]
env:
  # `BASE_URL` determines, relative to the root of the domain, the URL that your site is served from.
  # E.g., if your site lives at `https://mydomain.org/myproject`, set `BASE_URL=/myproject`.
  # If, instead, your site lives at the root of the domain, at `https://mydomain.org`, set `BASE_URL=''`.
  # BASE_URL: https://blog.ayghri.com
  CUSTOM_DOMAIN: https://blog.ayghri.com

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      # - name: Install MyST
        # run: npm install -g mystmd@1.6.3
      - name: clone custom MyST
        uses: actions/checkout@v4
        with:
          repository: ayghri/mystmd
          path: .cache/mystmd-fork
      - name: install custom myst
        working-directory: .cache/mystmd-fork
        run: |
          npm install
          npm run build
          npm run link

      - name: Build HTML Assets
        run: |
          myst build --html
          sed -i -e 's|http://localhost:3000|$CUSTOM_DOMAIN|g' $(grep -RIl "http://localhost:3000" ./_build)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
