### ISSUE TITLE
Numbering of headers and titles

### ISSUE THREAD

**Issue by vangeest** [jupyter-book/mystmd#2002]
## Description
Numbering of headings is not working as documented.

I'll provide 2 examples which can be reproduced in https://mystmd.org/sandbox

### Example 1
```
---
numbering:
  headings:
    enabled: true 
---
# top level heading
## sub level heading
### sub-sub level heading
```

Renders as
```
top level heading
1 sub level heading
1.1 sub-sub level heading
```
It should render as
```
1. top level heading
1.1 sub level heading
1.1.1 sub-sub level heading
```

### Example 2
```
---
title: "my title"
numbering:
  title:
    enabled: true
  heading_1:
    enabled: true 
  heading_2:
    enabled: true 
  heading_3:
    enabled: true 
---
# top level heading
## sub level heading
### sub-sub level heading
```

Renders as
```
my title
2 top level heading
2.1 sub level heading
2.1.1 sub-sub level heading
```

It should render either as
```
1. my title
1.1 top level heading
1.1.1 sub level heading
1.1.1.1 sub-sub level heading
```
or as:
```
1. my title
2. top level heading
2.1 sub level heading
2.1.1 sub-sub level heading
 ```

## Proposed solution
Adjust code to work according to documentation

## Additional notes
tested with Myst v1.3.26
documentation link: https://mystmd.org/guide/cross-references#title-numbering
