### ISSUE TITLE
Allow users to specify multiple style files

### ISSUE THREAD

**Issue by stefanv** [jupyter-book/mystmd#2022]
It would be convenient to be able to set styling for different groups of components, e.g.:

```
site:
  options:
    style:
      - footer.css
      - header.css
      - blog.css
```

**Comment by choldgraf** [comment]
Would a reasonable workaround be recommending users use an `SCSS` or `SASS` compiler? For example:

File one:

```scss
// _header.scss
header {
  padding: 10px;
}
```

File two:

```scss
// _button.scss
.btn {
  padding: 8px 15px;
}
```

file 3:

```scss
// main.scss
@import 'header';
@import 'button';

body {
  margin: 0;
  font-family: sans-serif;
}
```

Then provide instructions for how to generate a single CSS file with `sass` as a pre-build command, like

```bash
sass main.scss style.css
```

And then instruct users to link `style.css` in their MyST theme.

### Another option: bundle an scss compiler

I've also seen HTML generators bundle an scss compiler as a dependency, and that way you could parse the `style.css` file _as scss_ so the logic wouldn't need a separate compile command.
