### ISSUE TITLE
Cache item not found

### ISSUE THREAD

**Issue by pdimens** [jupyter-book/mystmd#2131]
Hello, thanks for making this tool, it's an amazing piece of work! Lately, I've been trying to have my site built and deployed using the provided Github action, but the builds are failing with a specific error:

```
ENOENT: no such file or directory, open '_build/cache/config-item-95d746199f3d8a6db59d0b2fb4ae043a.png'
```

Version as provided by the Action:
```
 Myst CLI Versions:
 - node                        18.20.8     Required: >= 18.0.0      
 - npm                          10.8.2     Required: >=8.6.0        
 - myst                          1.5.0     
```

## Additional notes
I'm not sure what the source of this is, as I don't have a local `_build` folder, so everything must be being generated during the build/deploy process.

**Comment by rowanc1** [comment]
Thanks for the report @pdimens. It would be helpful to have a reproducible example or pointer to the repo if available publicly?

It might be possible that you are converting images (e.g. from tiff or pdf?) and the action doesn't have the right things installed for that. It is a bit hard to tell from the cache error specifically!

**Comment by pdimens** [comment]
Sure thing, sorry about that. The repo is here: https://github.com/pdimens/haplotagging_simulations

To my knowledge, I don't have any pdfs or such, just two remote PNGs here, that I think might be the problem now (it wasn't an problem before)

```yaml
  options:
    favicon: https://www.therkildsenlab.org/uploads/1/4/5/5/145548022/published/new-logo-smaller.png
    logo: https://www.therkildsenlab.org/uploads/1/4/5/5/145548022/published/new-logo-smaller.png
```
