### ISSUE TITLE
[jtex] add a "list" options type to `jtex`

### ISSUE THREAD

**Issue by stevejpurves** [jupyter-book/mystmd#313]
### Which area is this feature request for?

Javascript Packages (please list)

### Describe the feature you'd like to request

`jtex` provides for certain template options [as documented here](https://myst-tools.org/docs/jtex/template-yml#template-options). 

However, it is not possible to specify a "list" option to allow a list of strings to be provided to the template via document frontmatter. This is similar to the `keywords` field in the document model but is freeform and can be specified by the template author.

### Describe the solution you'd like

a new option type `list` which allows a list of string to be provided. 

The `template.yml`entry would be:

```
- id: highlights
  type: list
  default: []
  required: false
```

The document frontmatter would then accept:

```
exports:
   - format: pdf
      highlights:
         - Highlight 1
         - Highlight 2
         - >
           a very long long long
           highlight as a multiline string which
           maybe is a bit too long for a highlight anyways
         - Highlight 4
```

This would resolve the issue in this template: https://github.com/myst-templates/cageo/issues/1

### Describe alternatives you've considered

In this template https://github.com/myst-templates/cageo/issues/1, we tried using parts to represent the highlights list but that results in additional unwanted latex environment being rendered.

with this change that template could include hte list of highlight with more control, e.g.

```
[# for highlight in options.highlights #]
\item{[-highlight-]}
[# endfor #]
```
