### ISSUE TITLE
Warning after following docs' instructions for configuring analytics

### ISSUE THREAD

**Issue by santisoler** [jupyter-book/mystmd#834]
Hi! First of all, thanks a lot for developing Myst! I really appreciate the effort all of you put into it  :rocket:

## Description

After following the instructions on [how to configure analytics](https://mystmd.org/guide/analytics), I get a warning stating that the `analytics_plausible` key should be nested under `"options"`. I suspect the instructions in the docs are outdated and should be updated.

Here I leave a minimal example that can reproduce this warning.

1. Clone the quickstart repo:
   ```
   git clone https://github.com/executablebooks/mystmd-quickstart.git
   cd mystmd-quickstart
   ```
1. Create a new `myst.yml` file that includes a line configuring the analytics through the `analytics_plausible` key nested inside `site`, as the docs instructs:
   ```yml
   # See docs at: https://mystmd.org/guide/frontmatter
   version: 1
   project:
     # title:
     # description:
     keywords: []
     authors: []
     github: https://github.com/executablebooks/mystmd-quickstart
     # bibliography: []
   site:
     template: book-theme
     # title:
     # options:
     #   logo: site_logo.png
     nav: []
     actions:
       - title: Learn More
         url: https://mystmd.org/guide
     domains: []
     # Add analytics
     analytics_plausible: mystmd.org # Domain(s) to track
   ```
1. Build the website with `myst`:
   ```
   myst build
   ```

The last command gives the following output:

```
⚠️  myst.yml extra site options should be nested under "options" key: analytics_plausible                
🌎 Building MyST site                                                                                   
📖 Built README.md in 76 ms.                                                                            
📖 Built 01-paper.md in 73 ms.                                                                          
📖 Built 02-notebook.ipynb in 65 ms.                                                                    
⚠️  _build/site/public/citations-bde29672608abb7ee2680f5e8412d1d1.png Could not convert from image _build/site/public/citations-bde29672608abb7ee2680f5e8412d1d1.png to webp:                                    
cwebp is required                                                                                       
                                                                                                        
⚠️  _build/site/public/equations-e661c8f673c584829298052d9365ed23.gif Could not convert from image _build/site/public/equations-e661c8f673c584829298052d9365ed23.gif to webp:                                    
gif2webp is required                                                                                    
                                                                                                        
⚠️  _build/site/public/interactive-cbc72f0575cfb35edd250daed1a14f7a.gif Could not convert from image _build/site/public/interactive-cbc72f0575cfb35edd250daed1a14f7a.gif to webp:                                
gif2webp is required                                                                                    
                                                                                                        
⚠️  _build/site/public/structured-data-455ad46debdcf2582054b9cef93ae0ea.gif Could not convert from image _build/site/public/structured-data-455ad46debdcf2582054b9cef93ae0ea.gif to webp:                        
gif2webp is required                                                                                    
                                                                                                        
⚠️  _build/site/public/pdf-two-column-11c0c26a3b4b51da1af8498eca260fde.png Could not convert from image _build/site/public/pdf-two-column-11c0c26a3b4b51da1af8498eca260fde.png to webp:                          
cwebp is required                                                                                       
                                                                                                        
⚠️  _build/site/public/citations-bde29672608abb7ee2680f5e8412d1d1.png Could not convert from image _build/site/public/citations-bde29672608abb7ee2680f5e8412d1d1.png to webp:                                    
cwebp is required                                                                                       
                                                                                                        
⚠️  _build/site/public/frontmatter-after-b2b4a3272457fa951bfce1b0e34963a3.png Could not convert from image _build/site/public/frontmatter-after-b2b4a3272457fa951bfce1b0e34963a3.png to webp:                    
cwebp is required                                                                                       
                                                                                                        
⚠️  _build/site/public/export-pdf-1be7d0647a9ef07895cb8ff0df302ad5.png Could not convert from image _build/site/public/export-pdf-1be7d0647a9ef07895cb8ff0df302ad5.png to webp:                                  
cwebp is required                                                                                       
                                                                                                        
📚 Built 3 pages for project in 400 ms.                                                                 
🔍 Querying template metadata from https://api.mystmd.org/templates/site/myst/book-theme                
🐕 Fetching template from https://github.com/myst-templates/book-theme/archive/refs/heads/main.zip      
💾 Saved template to path _build/templates/site/myst/book-theme
```

Myst is complaining about having `analytics_plausible` nested under `site` and not under `options`.

I get this warning on `myst=v1.1.37`.

## Proposed solution

If I'm right and the documentation is outdated, then we should update it.

For configuring Google Analytics it should be:
```yml
version: 1
site:
  options:
    analytics_google: UA-XXXXX # Measurement ID or Tracking ID
```

And for Plausible:
```yml
version: 1
site:
  options:
    analytics_plausible: mystmd.org # Domain(s) to track
```
